### PR TITLE
move config.ini and /models to /etc/howdy

### LINKED ISSUE #594: Cannot work on Fedora Silverblue or any CoreOS derivatives
I have installed howdy on Fedora Silverblue by using package layering. Howdy requires write access to `/usr/lib64/security/howdy` to update `config.ini` and to create `models`. Silverblue and CoreOS derivatives keep the `/usr` file-system read-only and if any change is made to the file-system, its original state will be restored after a reboot. On Silverblue, configuration files are persisted by writing them to `/etc`. To solve this issue all it's needed is to keep `config.ini` and the `models` directory under `/etc`, for example `/etc/howdy/config.ini` and `/etc/howdy/models`.
It would probably make sense to change the paths for all distros, not just for Silverblue.

I'd be happy to contribute the code changes myself, if someone with experience with this codebase is available for some support. One of the thing that I haven't figure out is which branch I should be contributing to.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Fedora Silverblue

Howdy version (`sudo howdy version`): Howdy 2.6.1

### PR DESCRIPTION
**Pull request by patriziobruno**
For better compatibility with immutable OSs like Fedora Silverblue and all CoreOS derivatives. Immutable OSs give the user write access only to the `/etc` directory.

Fixes #594

### CODE REVIEW

**Comment by NikSays** [comment]
Thank you so much for your effort, hope this will be merged.

One question though: what about snapshots? It seems that /src/snapshot.py creates the snapshots folder next to itself in /usr/lib/

Maybe it should be moved to somewhere like /var/log/howdy  ?

**Comment by boltgolt** [comment]
Seems like a good suggestion, same for the /var/log idea. I also want to move the current folder location in general as /lib/security was for pam-python compatibility before, maybe /usr/bin would be better

**Comment by boltgolt** [comment]
See #669 for other good points, @Zocker1999NET what do you think of my point above, moving the actual binaries/python files to somewhere that's not `/lib/security`?

**Comment by Zocker1999NET** [comment]
> See #669 for other good points, @Zocker1999NET what do you think of my point above, moving the actual binaries/python files to somewhere that's not `/lib/security`?

@boltgolt `/lib/security` or `/lib` seem both reasonable enough for binaries because `/bin` e.g. is reserved for commands a normal user would execute in a shell and only the `howdy` command itself would qualify for it IMO. Then only `/usr/share` comes to my mind as another option, which would be applicable for architecture independent data (logos, reference models, python files). But keeping all data where it is stored now seems reasonable enough as well.

**Comment by boltgolt** [comment]
Thanks for the changes, finally merged!

**Comment by SRF-Audio** [comment]
Hey all...so I see this changes, but I'm trying to figure out a good way to install this on [Aurora DX](https://getaurora.dev/). 

When I try to layer the packages manually I get into some dependency issues:

```
rpm-ostree install ~/Downloads/howdy-2.6.1-10.fc41.x86_64.rpm       
Checking out tree 96923cb... done
Enabled rpm-md repositories: 1password copr:copr.fedorainfracloud.org:lukenukem:asus-linux updates fedora copr:copr.fedorainfracloud.org:gmaglione:podman-bootc copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr linux-surface updates-archive
Importing rpm-md... done
rpm-md repo '1password' (cached); generated: 2024-12-12T19:24:00Z solvables: 2
rpm-md repo 'copr:copr.fedorainfracloud.org:lukenukem:asus-linux' (cached); generated: 2024-08-30T10:56:31Z solvables: 5
rpm-md repo 'updates' (cached); generated: 2025-01-07T02:40:46Z solvables: 16209
rpm-md repo 'fedora' (cached); generated: 2024-10-24T13:55:59Z solvables: 76624
rpm-md repo 'copr:copr.fedorainfracloud.org:gmaglione:podman-bootc' (cached); generated: 2024-12-11T04:49:17Z solvables: 5
rpm-md repo 'copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr' (cached); generated: 2024-10-25T08:11:34Z solvables: 5
rpm-md repo 'linux-surface' (cached); generated: 2024-12-28T15:53:38Z solvables: 34
rpm-md repo 'updates-archive' (cached); generated: 2025-01-07T02:55:14Z solvables: 20815
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides pam_python needed by howdy-2.6.1-10.fc41.x86_64 from @commandline
```

Then:
```
rpm-ostree install ~/Downloads/pam_python-1.0.8-4.fc41.x86_64.rpm       
Checking out tree 96923cb... done
Enabled rpm-md repositories: 1password copr:copr.fedorainfracloud.org:lukenukem:asus-linux updates fedora copr:copr.fedorainfracloud.org:gmaglione:podman-bootc copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr linux-surface updates-archive
Importing rpm-md... done
rpm-md repo '1password' (cached); generated: 2024-12-12T19:24:00Z solvables: 2
rpm-md repo 'copr:copr.fedorainfracloud.org:lukenukem:asus-linux' (cached); generated: 2024-08-30T10:56:31Z solvables: 5
rpm-md repo 'updates' (cached); generated: 2025-01-07T02:40:46Z solvables: 16209
rpm-md repo 'fedora' (cached); generated: 2024-10-24T13:55:59Z solvables: 76624
rpm-md repo 'copr:copr.fedorainfracloud.org:gmaglione:podman-bootc' (cached); generated: 2024-12-11T04:49:17Z solvables: 5
rpm-md repo 'copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr' (cached); generated: 2024-10-25T08:11:34Z solvables: 5
rpm-md repo 'linux-surface' (cached); generated: 2024-12-28T15:53:38Z solvables: 34
rpm-md repo 'updates-archive' (cached); generated: 2025-01-07T02:55:14Z solvables: 20815
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides libpython2.7.so.1.0()(64bit) needed by pam_python-1.0.8-4.fc41.x86_64 from @commandline
```

Then:
```
rpm-ostree install ~/Downloads/lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64.rpm 
Checking out tree 96923cb... done
Enabled rpm-md repositories: 1password copr:copr.fedorainfracloud.org:lukenukem:asus-linux updates fedora copr:copr.fedorainfracloud.org:gmaglione:podman-bootc copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr linux-surface updates-archive
Importing rpm-md... done
rpm-md repo '1password' (cached); generated: 2024-12-12T19:24:00Z solvables: 2
rpm-md repo 'copr:copr.fedorainfracloud.org:lukenukem:asus-linux' (cached); generated: 2024-08-30T10:56:31Z solvables: 5
rpm-md repo 'updates' (cached); generated: 2025-01-07T02:40:46Z solvables: 16209
rpm-md repo 'fedora' (cached); generated: 2024-10-24T13:55:59Z solvables: 76624
rpm-md repo 'copr:copr.fedorainfracloud.org:gmaglione:podman-bootc' (cached); generated: 2024-12-11T04:49:17Z solvables: 5
rpm-md repo 'copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr' (cached); generated: 2024-10-25T08:11:34Z solvables: 5
rpm-md repo 'linux-surface' (cached); generated: 2024-12-28T15:53:38Z solvables: 34
rpm-md repo 'updates-archive' (cached); generated: 2025-01-07T02:55:14Z solvables: 20815
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides python(abi) = 2.7 needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
  - nothing provides python2 = 2.7.18-7.2.mga8 needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
  - nothing provides libcrypto.so.1.1()(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
  - nothing provides libcrypto.so.1.1(OPENSSL_1_1_0)(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
  - nothing provides libintl.so.8()(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
  - nothing provides libnsl.so.2()(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
  - nothing provides libnsl.so.2(LIBNSL_1.0)(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
  - nothing provides libpython2.7.so.1.0()(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
  - nothing provides libssl.so.1.1()(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
  - nothing provides libssl.so.1.1(OPENSSL_1_1_0)(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline

```

And on it goes.

Any way to get this into HomeBrew?

**Comment by fritzcloud** [comment]
> Hey all...so I see these changes, but I'm trying to figure out a good way to install this on [Aurora DX](https://getaurora.dev/).
> 
> When I try to layer the packages manually I get into some dependency issues:
> 
> ```
> rpm-ostree install ~/Downloads/howdy-2.6.1-10.fc41.x86_64.rpm       
> Checking out tree 96923cb... done
> Enabled rpm-md repositories: 1password copr:copr.fedorainfracloud.org:lukenukem:asus-linux updates fedora copr:copr.fedorainfracloud.org:gmaglione:podman-bootc copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr linux-surface updates-archive
> Importing rpm-md... done
> rpm-md repo '1password' (cached); generated: 2024-12-12T19:24:00Z solvables: 2
> rpm-md repo 'copr:copr.fedorainfracloud.org:lukenukem:asus-linux' (cached); generated: 2024-08-30T10:56:31Z solvables: 5
> rpm-md repo 'updates' (cached); generated: 2025-01-07T02:40:46Z solvables: 16209
> rpm-md repo 'fedora' (cached); generated: 2024-10-24T13:55:59Z solvables: 76624
> rpm-md repo 'copr:copr.fedorainfracloud.org:gmaglione:podman-bootc' (cached); generated: 2024-12-11T04:49:17Z solvables: 5
> rpm-md repo 'copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr' (cached); generated: 2024-10-25T08:11:34Z solvables: 5
> rpm-md repo 'linux-surface' (cached); generated: 2024-12-28T15:53:38Z solvables: 34
> rpm-md repo 'updates-archive' (cached); generated: 2025-01-07T02:55:14Z solvables: 20815
> Resolving dependencies... done
> error: Could not depsolve transaction; 1 problem detected:
>  Problem: conflicting requests
>   - nothing provides pam_python needed by howdy-2.6.1-10.fc41.x86_64 from @commandline
> ```
> 
> Then:
> 
> ```
> rpm-ostree install ~/Downloads/pam_python-1.0.8-4.fc41.x86_64.rpm       
> Checking out tree 96923cb... done
> Enabled rpm-md repositories: 1password copr:copr.fedorainfracloud.org:lukenukem:asus-linux updates fedora copr:copr.fedorainfracloud.org:gmaglione:podman-bootc copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr linux-surface updates-archive
> Importing rpm-md... done
> rpm-md repo '1password' (cached); generated: 2024-12-12T19:24:00Z solvables: 2
> rpm-md repo 'copr:copr.fedorainfracloud.org:lukenukem:asus-linux' (cached); generated: 2024-08-30T10:56:31Z solvables: 5
> rpm-md repo 'updates' (cached); generated: 2025-01-07T02:40:46Z solvables: 16209
> rpm-md repo 'fedora' (cached); generated: 2024-10-24T13:55:59Z solvables: 76624
> rpm-md repo 'copr:copr.fedorainfracloud.org:gmaglione:podman-bootc' (cached); generated: 2024-12-11T04:49:17Z solvables: 5
> rpm-md repo 'copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr' (cached); generated: 2024-10-25T08:11:34Z solvables: 5
> rpm-md repo 'linux-surface' (cached); generated: 2024-12-28T15:53:38Z solvables: 34
> rpm-md repo 'updates-archive' (cached); generated: 2025-01-07T02:55:14Z solvables: 20815
> Resolving dependencies... done
> error: Could not depsolve transaction; 1 problem detected:
>  Problem: conflicting requests
>   - nothing provides libpython2.7.so.1.0()(64bit) needed by pam_python-1.0.8-4.fc41.x86_64 from @commandline
> ```
> 
> Then:
> 
> ```
> rpm-ostree install ~/Downloads/lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64.rpm 
> Checking out tree 96923cb... done
> Enabled rpm-md repositories: 1password copr:copr.fedorainfracloud.org:lukenukem:asus-linux updates fedora copr:copr.fedorainfracloud.org:gmaglione:podman-bootc copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr linux-surface updates-archive
> Importing rpm-md... done
> rpm-md repo '1password' (cached); generated: 2024-12-12T19:24:00Z solvables: 2
> rpm-md repo 'copr:copr.fedorainfracloud.org:lukenukem:asus-linux' (cached); generated: 2024-08-30T10:56:31Z solvables: 5
> rpm-md repo 'updates' (cached); generated: 2025-01-07T02:40:46Z solvables: 16209
> rpm-md repo 'fedora' (cached); generated: 2024-10-24T13:55:59Z solvables: 76624
> rpm-md repo 'copr:copr.fedorainfracloud.org:gmaglione:podman-bootc' (cached); generated: 2024-12-11T04:49:17Z solvables: 5
> rpm-md repo 'copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr' (cached); generated: 2024-10-25T08:11:34Z solvables: 5
> rpm-md repo 'linux-surface' (cached); generated: 2024-12-28T15:53:38Z solvables: 34
> rpm-md repo 'updates-archive' (cached); generated: 2025-01-07T02:55:14Z solvables: 20815
> Resolving dependencies... done
> error: Could not depsolve transaction; 1 problem detected:
>  Problem: conflicting requests
>   - nothing provides python(abi) = 2.7 needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
>   - nothing provides python2 = 2.7.18-7.2.mga8 needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
>   - nothing provides libcrypto.so.1.1()(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
>   - nothing provides libcrypto.so.1.1(OPENSSL_1_1_0)(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
>   - nothing provides libintl.so.8()(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
>   - nothing provides libnsl.so.2()(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
>   - nothing provides libnsl.so.2(LIBNSL_1.0)(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
>   - nothing provides libpython2.7.so.1.0()(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
>   - nothing provides libssl.so.1.1()(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
>   - nothing provides libssl.so.1.1(OPENSSL_1_1_0)(64bit) needed by lib64python2.7-stdlib-2.7.18-7.2.mga8.x86_64 from @commandline
> ```
> 
> And on it goes.
> 
> Any way to get this into HomeBrew?

Did you ever find a way to get it running on Aurora?

**Pull request merged**
