### PR TITLE
Update .SRCINFO

### PR DESCRIPTION
**Pull request by ymatsiuk**
Fixes: ` -> pam-python: local (1.0.7-1) is newer than AUR (1.0.6-1)`

### CODE REVIEW

**Comment by boltgolt** [comment]
@kageurufu @Raymo111 @xuanruiqi

Thoughts?

**Comment by Raymo111** [comment]
I don't know how @kageurufu is doing it now, but srcinfo should be generated via `makepkg --printsrcinfo > .SRCINFO`.

**Comment by xuanruiqi** [comment]
@Raymo111 is right. And IMO we really shouldn't be checking .SRCINFO into this repo.

Outlook for Android<https://aka.ms/ghei36> を入手

________________________________

**Comment by kageurufu** [comment]
Sorry, missed .SRCINFO in my push to the aur, its fixed there now. 

I'm fine removing .SRCINFO from this repo

**Pull request closed without merging**
