### PR TITLE
rename wrong attribute name to prevent AttributeError Python Exception

### PR DESCRIPTION
**Pull request by NP-chaonay**
according to https://github.com/boltgolt/howdy/issues/671

also pls applied on both beta/dev branch

### CODE REVIEW

**Comment by boltgolt** [comment]
Thank you! The file structure of the project is different now on the target beta branch. Could you fix the conflict?

**Comment by NP-chaonay** [comment]
> Thank you! The file structure of the project is different now on the target beta branch. Could you fix the conflict?

It seem that I use origin of branch "dev", so it have problem when PR to target branch "beta".
in that case I think new PR is required or instead editing code manually.

I'm not fond of GitHub too much btw.

**Comment by boltgolt** [comment]
Beta is the current target and default branch unfortunately, but you should be able to rebase? Otherwise opening a new PR is not a problem at all

**Comment by NP-chaonay** [comment]
Move to #673

**Pull request closed without merging**
