### PR TITLE
build: add meson build system 

### LINKED ISSUE #836: Beta crashes with no face model known
While testing beta version I discovered that when there is no face model known for user, then howdy crashes with this error:

```
Child killed by signal User defined signal 1 (10)
```

However, this error is definitely not right. 'pam_howdy' is detecting 'no face model' there (checked it):

https://github.com/boltgolt/howdy/blob/f7649fc922b5b7877146d00d0475bad9d6453531/howdy/src/pam/main.cc#L254-L259

Error steps:
1. 'no face model' check fails
2. howdy_status is called
3. status isn't success, so howdy_error is called
   https://github.com/boltgolt/howdy/blob/f7649fc922b5b7877146d00d0475bad9d6453531/howdy/src/pam/main.cc#L112-L117
4. status isn't child return value or signal (undefined behaviour probably? (idk how `WIFEXITED` and `WIFSIGNALED` work))
   https://github.com/boltgolt/howdy/blob/f7649fc922b5b7877146d00d0475bad9d6453531/howdy/src/pam/main.cc#L59-L65
5. second if is executed
   https://github.com/boltgolt/howdy/blob/f7649fc922b5b7877146d00d0475bad9d6453531/howdy/src/pam/main.cc#L89-L93
6. 'Child killed...' message logged
   https://github.com/boltgolt/howdy/blob/f7649fc922b5b7877146d00d0475bad9d6453531/howdy/src/pam/main.cc#L92-L96
7. error is returned to pam
   https://github.com/boltgolt/howdy/blob/f7649fc922b5b7877146d00d0475bad9d6453531/howdy/src/pam/main.cc#L98-L101

Maybe separate function to detect type of CompareError and what happened to child will be a good solution? What do you think?

Error created in #824 in a5184dc663969960dd1cd7a543ff2df646e22392

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Fedora 38

Howdy version (`sudo howdy version`): Howdy 3.0.0 BETA

### PR DESCRIPTION
**Pull request by musikid**
Based on #773, add Meson as a build system for the whole howdy package,
which allows better flexibility for the paths' configuration.
Generate a python module,
which contains the paths used by the other modules,
by using `PurePath` to simplify path concatenation and limit errors,
and the header containing the paths for the PAM module.

Closes #836

### CODE REVIEW

**Comment by boltgolt** [comment]
Lovely! I would say this supersedes the other path PR #773?

**Comment by musikid** [comment]
Yes, it includes the commit from the other PR and takes it a step further with Meson.

**Comment by musikid** [comment]
Should we first merge this PR and progressively create the remaining parts on other PRs, or merge all the changes on this one?

**Comment by boltgolt** [comment]
Amazing, i've merged beta into your branch and that should hopefully be clean now. Any other PRs that i merge i'll make sure will use your new path factory system. Please check if my merge commit did not fuck anything up, and as i've made you collaborator you should be able to merge it yourself if it's all good! Thanks for all you do for Howdy!

**Comment by musikid** [comment]
> Amazing, i've merged beta into your branch and that should hopefully be clean now. Any other PRs that i merge i'll make sure will use your new path factory system. Please check if my merge commit did not fuck anything up, and as i've made you collaborator you should be able to merge it yourself if it's all good! Thanks for all you do for Howdy!

Thanks, you're welcome!

**Comment by musikid** [comment]
I added the latest changes for user model checking and fixed all the remaining problems, it can be now merged!

**Comment by boltgolt** [comment]
Merged :tada: Thanks again!

**Pull request merged**
