### PR TITLE
 Fix :"Unknown error: 1" on gnome-screensaver

### PR DESCRIPTION
**Pull request by calvinweb**

### CODE REVIEW

**Comment by boltgolt** [comment]
Interesting patch, could you describe what it does and why? Emptying $PATH is a very large step to take

**Comment by calvinweb** [comment]
> Interesting patch, could you describe what it does and why? Emptying $PATH is a very large step to take

because some librarys(eg. different verision of dlib and opencv) may make it dosn't work

**Comment by boltgolt** [comment]
I can see why this fixes that, but i would anticipate that for others this change would break their previously working setup. Unfortunately i'm going to have to decline this change but thanks for submitting it!

**Comment by calvinweb** [comment]
but it only effect in python life cycle ,pleace open it again

**Comment by boltgolt** [comment]
But what if people use pyenv to make sure Howdy runs in python3? Clearing the $PATH will completely break Howdy for them.
Additionally, the check that the path starts with /home seems completely arbitrary to me

**Comment by calvinweb** [comment]
it isn't environment var,it only a var in python runtime

**Comment by calvinweb** [comment]
but i think this is a mistake from python,python should find libraries from system paths at first

**Pull request closed without merging**
