### PR TITLE
Version 2.5.0

### PR DESCRIPTION
**Pull request by boltgolt**
**Changelog:**
  * Added FFmpeg and v4l2 recorders (thanks @timwelch!)
  * Added automatic PAM inclusion on installation
  * Added optional notice on detection attempt (thanks @mrkmg!)
  * Added support for grayscale frame encoding (thanks @dmig and @sapjunior!)
  * Massively improved recognition speed (thanks @dmig!)
  * Fixed typo in "timout" config value
  * Removed unneeded dependencies (thanks @dmig!)

### CODE REVIEW

**Comment by boltgolt** [comment]
This is a fix for issues #70, #99, #105 and #107

**Comment by boltgolt** [comment]
@luyatshimbalanga @KelleyMcChes if you have the time, could you release 2.5.0 on your respective distros?

**Comment by luyatshimbalanga** [comment]
@boltgolt Would you list the requirement for the new 2.5.0 release? I attempt to built it but it failed. Also will it be possible to build without ffmpeg as the Fedora policy does allow ffmpeg in the repository?

**Comment by boltgolt** [comment]
@luyatshimbalanga what do you mean by requirements? Using ffmpeg directly from the fedora repositories should be no problem.

**Pull request merged**
