### PR TITLE
Simpler archlinux PKGBUILD - Separate pam-python and use the existing python-dlib and python-face_recognition packages

### PR DESCRIPTION
**Pull request by kageurufu**
Installing howdy currently uses a monolithic PKGBUILD which installs python-face_recognition and python-dlib internally. The existing packages for these on the AUR work completely fine in place. pam-python is also installed, but its cleaner and fits the Arch KISS mentality to have a separate package for pam-python.

This PR adds a separate pam-python PKGBUILD which would need to be added to the aur, and includes a far simpler howdy PKGBUILD that also pulls in the dlib models during packaging time instead of requiring the user to go run a bash script to manually download the models.

### CODE REVIEW

**Comment by boltgolt** [comment]
Sorry, i missed this completely last month. I'll take a closer look at your changes tomorrow but they look great!

**Comment by kageurufu** [comment]
Hey, I see your looking for a maintainer for Arch, i've got a lot of experience maintaining AUR packages, and would be happy to volunteer my time. Just let me know if you're interested and what you need

**Comment by xuanruiqi** [comment]
Any plans to merge this?

**Comment by kageurufu** [comment]
@boltgolt if you want to just add me as a maintainer on the AUR, I can just start maintaining things there. I'm [kageurufu](https://aur.archlinux.org/account/kageurufu/) there as well

**Pull request merged**
