### PR TITLE
Initial FFMPEG support for HP Spectre x360 13t IR camera

### PR DESCRIPTION
**Pull request by timwelch**
Fixes HP Spectre x360 13t IR camera issue. The IR camera is detected by OpenCV but fails to work properly. FFMPEG works using /dev/video2 device. Added an ffmpeg class that mimics the behavior 
 and currently used functions of opencv.

### CODE REVIEW

**Comment by timwelch** [comment]
Looks like the tests are failing outside of the scope of things I changed. Unless I'm looking at the travis build incorrectly. Not sure what pam.sh does, but I don't believe that was me.

**Comment by boltgolt** [comment]
The tests failing are not your fault. I was working on them but haven't fixed that part yet. Your changes look very nice though, i'll merge it later today.

**Comment by timwelch** [comment]
last two commits reduces probing for resolution by ~700ms.

```
tim@loveprayserve:~$ sudo echo howdy
Time spent
  Starting up: 120ms
  Opening the camera: 1161ms
  Importing face_recognition: 1067ms
  Searching for known face: 105ms

Resolution
  Native: 352x352
  Used: 320x320

Frames searched: 1 (9.49 fps)
Dark frames ignored: 0 
Certainty of winning frame: 3.062
Winning model: 0 ("Initial model")
Identified face as tim
howdy
```

**Comment by boltgolt** [comment]
I've changed a few things mostly for readability and ease of use but the overal code is excellent. Thanks so much for your work!

**Pull request merged**
