### PR TITLE
Added notification popup when it's running

### PR DESCRIPTION
**Pull request by Ev1lbl0w**
Added a notification/popup *(through `notify-send`)* to notify the user when the app is scanning faces.

The message, timeout and icon of the notification are examples, so they're obviously open for change.

I also made this feature optional by adding it to `config.ini`*(by default it's active: again, open for change)*

### CODE REVIEW

**Comment by zeka001** [comment]
I don't think this feature is useful, why I will like to have a notification when the app is running? I know how my system works and what I have install. Anyway, at least don't make it active by default, I will vote for that.

**Comment by reverland** [comment]
In fact I always feel the system freezes at the beginning, before I realize its howdy hardly trying to recognize me.

**Comment by boltgolt** [comment]
First of all, thanks a lot for immediately making a PR for something you'd like to see in Howdy! I've been working on a GUI very much like the one [fingerprint-gui has](http://www.ullrich-online.cc/fingerprint/doc/test.png) while authenticating, but this would help a lot in the meantime. 

I'm curious though, what does this option do for you guys that the `detection_notice` config option does not?

**Comment by Ev1lbl0w** [comment]
> I'm curious though, what does this option do for you guys that the `detection_notice` config option does not?

Uh. The AUR package seems to be outdated, because I didn't realize something similar was already implemented. My bad :wink: 

So I think the only difference here is that one is a popup, and the other is a text message. But I actually believe your solution is much better, since it works in situations `notify-send` doesn't *(like lightdm)*.

Feel free to close this PR, I now noticed this is redundant.

**Comment by boltgolt** [comment]
The arch package is behind 2 version compared to the Debian and Fedora releases, it's being tracked in #122. I'm gonna close this PR then, but once again thanks a lot for merging your changes back into Howdy!

**Pull request closed without merging**
