### PR TITLE
Added custom error for VideoCapture

### PR DESCRIPTION
**Pull request by CoderThomasB**
fix issue #569

### CODE REVIEW

**Comment by CoderThomasB** [comment]
#569

**Comment by CoderThomasB** [comment]
Screenshot from 2021-07-17 10-19-21-2
I've tested it and it should be working!

**Comment by boltgolt** [comment]
Changes look good! Unfortunately pam.py is going to be replaced by a rewrite in c++. I'm going to keep this PR open so it can me merged once those changes are done

**Comment by boltgolt** [comment]
Implemented in the new code structure, thank you!

**Pull request closed without merging**
